# Generated by Django 2.2.4 on 2019-09-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0014_heroe_took_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='army',
            name='took_part_events',
            field=models.ManyToManyField(null=True, to='mains.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(null=True, to='mains.heroe'),
        ),
    ]
