# Generated by Django 2.2.4 on 2019-09-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0016_auto_20190920_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='army',
            name='took_part_events',
            field=models.ManyToManyField(blank=True, to='mains.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, to='mains.heroe'),
        ),
    ]
