# Generated by Django 2.2.4 on 2019-10-04 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0017_auto_20190920_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mains.date'),
        ),
    ]
